---
- name: Display Primary DC and CA host
  ansible.builtin.debug:
    msg: "DC: {{ ludus_adcs_dc }} | CA: {{ ludus_adcs_ca_host }}"

- name: Create an ESC16 domain user
  community.windows.win_domain_user:
    name: "{{ ludus_adcs_esc16_user }}"
    password: "{{ ludus_adcs_esc16_password }}"
    upn: "{{ ludus_adcs_esc16_user }}"
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    domain_username: "{{ ludus_adcs_domain_username }}"
    domain_password: "{{ ludus_adcs_domain_password }}"
    domain_server: "{{ ludus_adcs_dc }}"

- name: Copy ESC16 ACLs script to remote host
  ansible.windows.win_copy:
    src: files/esc16.ps1
    dest: C:\ludus\adcs\esc16.ps1

- name: Run ESC16 script
  ansible.windows.win_shell: |
    C:\ludus\adcs\esc16.ps1 -esc16user '{{ ludus_adcs_esc16_user }}' | Select-String -Pattern 'Domain Users'
  become: true
  become_method: runas
  vars:
    ansible_become: true
    ansible_become_method: runas
    domain_name: "{{ ludus_adcs_domain }}"
    ansible_become_user: "{{ ludus_adcs_domain_username }}"
    ansible_become_password: "{{ ludus_adcs_domain_password }}"
  register: esc16_output

- name: Output ESC16 ACLs script result
  ansible.builtin.debug:
    var: esc16_output

- name: "Configure szOID_NTDS_CA_SECURITY_EXT on CA - ESC16"
  ansible.windows.win_shell: |
    certutil -config "{{ cauthority_server }}\{{ cauthority_common_name }}" -setreg policy\DisableExtensionList +1.3.6.1.4.1.311.25.2
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ludus_adcs_domain_username }}"
    ansible_become_password: "{{ ludus_adcs_domain_password }}"
    cauthority_server: "{{ ludus_adcs_ca_host }}"
    cauthority_common_name: "{{ ludus_adcs_ca_common_name }}"
  when: ludus_adcs_esc16 is true