---
- name: Display Primary DC and CA host
  ansible.builtin.debug:
    msg: "DC: {{ ludus_adcs_dc }} | CA: {{ ludus_adcs_ca_host }}"

- name: Disable IF_ENFORCEENCRYPTICERTREQUEST flag
  ansible.windows.win_shell: |
    certutil -setreg CA\InterfaceFlags -IF_ENFORCEENCRYPTICERTREQUEST
  become: true
  become_method: runas
  vars:
    ansible_become: true
    ansible_become_method: runas
    domain_name: "{{ ludus_adcs_domain }}"
    ansible_become_user: "{{ ludus_adcs_domain_username }}"
    ansible_become_password: "{{ ludus_adcs_domain_password }}"
  register: esc11_flag_output

- name: Output IF_ENFORCEENCRYPTICERTREQUEST result
  ansible.builtin.debug:
    var: esc11_flag_output

- name: Stop ADCS
  ansible.windows.win_shell: |
    net stop certsvc
  become_method: runas
  vars:
    ansible_become: true
    ansible_become_method: runas
    domain_name: "{{ ludus_adcs_domain }}"
    ansible_become_user: "{{ ludus_adcs_domain_username }}"
    ansible_become_password: "{{ ludus_adcs_domain_password }}"
  register: esc11_stop_output

- name: Output Stop ADCS result
  ansible.builtin.debug:
    var: esc11_stop_output

- name: Start ADCS
  ansible.windows.win_shell: |
    net start certsvc
  become: true
  become_method: runas
  vars:
    ansible_become: true
    ansible_become_method: runas
    domain_name: "{{ ludus_adcs_domain }}"
    ansible_become_user: "{{ ludus_adcs_domain_username }}"
    ansible_become_password: "{{ ludus_adcs_domain_password }}"
  register: esc11_start_output

- name: Output ESC11 script result
  ansible.builtin.debug:
    var: esc11_start_output
