---
- name: Display Primary DC and CA host
  ansible.builtin.debug:
    msg: "DC: {{ ludus_adcs_dc }} | CA: {{ ludus_adcs_ca_host }}"

- name: Copy ESC15 script to remote host
  ansible.windows.win_copy:
    src: files/esc15.ps1
    dest: C:\ludus\adcs\esc15.ps1

- name: Run ESC15 script
  ansible.windows.win_shell: |
    C:\ludus\adcs\esc15.ps1
  become: true
  become_method: runas
  vars:
    ansible_become: true
    ansible_become_method: runas
    domain_name: "{{ ludus_adcs_domain }}"
    ansible_become_user: "{{ ludus_adcs_domain_username }}"
    ansible_become_password: "{{ ludus_adcs_domain_password }}"
