---
- name: Display Primary DC and CA host
  ansible.builtin.debug:
    msg: "DC: {{ ludus_adcs_dc }} | CA: {{ ludus_adcs_ca_host }}"

- name: Create an ESC7 CA Manager domain user
  community.windows.win_domain_user:
    name: "{{ ludus_adcs_esc7_ca_manager_user }}"
    password: "{{ ludus_adcs_esc7_ca_manager_password }}"
    upn: "{{ ludus_adcs_esc7_ca_manager_user }}"
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    domain_username: "{{ ludus_adcs_domain_username }}"
    domain_password: "{{ ludus_adcs_domain_password }}"
    domain_server: "{{ ludus_adcs_dc }}"

- name: Create an ESC7 Certificates Manager domain user
  community.windows.win_domain_user:
    name: "{{ ludus_adcs_esc7_cert_manager_user }}"
    password: "{{ ludus_adcs_esc7_cert_manager_password }}"
    upn: "{{ ludus_adcs_esc7_cert_manager_user }}"
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    domain_username: "{{ ludus_adcs_domain_username }}"
    domain_password: "{{ ludus_adcs_domain_password }}"
    domain_server: "{{ ludus_adcs_dc }}"

- name: Copy the PSPKI Module to CA
  win_copy:
    src: files/PSPKI/PSPKI
    dest: "C:\\Program Files\\WindowsPowerShell\\Modules"

- name: Copy ESC7 script to remote host
  ansible.windows.win_copy:
    src: files/esc7.ps1
    dest: "C:\\ludus\\adcs\\esc7.ps1"

- name: Run ESC7 script
  ansible.windows.win_shell: |
    C:\ludus\adcs\esc7.ps1 -caManagerUser '{{ ludus_adcs_esc7_ca_manager_user }}' -certManagerUser '{{ ludus_adcs_esc7_cert_manager_user }}'
  become: true
  become_method: runas
  vars:
    ansible_become: true
    ansible_become_method: runas
    domain_name: "{{ ludus_adcs_domain }}"
    ansible_become_user: "{{ ludus_adcs_domain_username }}"
    ansible_become_password: "{{ ludus_adcs_domain_password }}"
  register: esc7_output

- name: Output ESC7 script result
  ansible.builtin.debug:
    var: esc7_output
